docker-container: &docker-container
  plugins:
    - automattic/bash-cache#fix/docker-support
    - docker#v3.8.0:
        image: "public.ecr.aws/automattic/android-build-image:311ab824e9fd33ebb71de83c3fd1c328ea84443b"
        environment: [ "CACHE_BUCKET_NAME", "BUILDKITE_PIPELINE_SLUG", "BUILDKITE_LABEL" ]
        propagate-environment: true
        volumes:
         - "/var/lib/buildkite-agent/plugins/bash-cache:/bash-cache"

steps:
  - label: "checkstyle"
    <<: *docker-container
    command: |
      echo "--- â¤µï¸ Installing Bash Cache Plugin"
      cp -v /bash-cache/bin/* /usr/bin

      echo "---"
      echo $BUILDKITE_PLUGIN_BASH_CACHE_BUCKET
      echo "---"

      CACHEKEY="$BUILDKITE_PIPELINE_SLUG-$BUILDKITE_LABEL"

      echo "--- ðŸ§¹ Linting"

      restore_cache "$CACHEKEY"

      cp -v gradle.properties-example gradle.properties
      ./gradlew checkstyle

      save_cache /root/.android $CACHEKEY
      ls /root
      ls /root/.android
    artifact_paths:
      - "**/build/reports/checkstyle/checkstyle.*"

  - label: "detekt"
    <<: *docker-container
    command: |
      echo "--- ðŸ§¹ Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew detektAll
    artifact_paths:
      - "**/build/reports/detekt/detekt.html"

  - label: "lint"
    <<: *docker-container
    command: |
      echo "--- ðŸ§¹ Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew lintVanillaRelease
    artifact_paths:
      - "**/build/reports/lint-results*.*"

  - label: "Test WooCommerce"
    <<: *docker-container
    command: |
      echo "--- ðŸ§ª Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew testVanillaRelease

  - label: "Test CardReaderModule"
    <<: *docker-container
    command: |
      echo "--- ðŸ§ª Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew lib:cardreader:testRelease

  - label: "Ensure Screenshot Tests Build"
    <<: *docker-container
    command: |
      echo "--- âš’ï¸ Building"
      cp gradle.properties-example gradle.properties
      ./gradlew assembleVanillaDebugAndroidTest