docker-container: &docker-container
  plugins:
    - automattic/bash-cache#fix/docker-support
    - docker#v3.8.0:
        image: "public.ecr.aws/automattic/android-build-image:311ab824e9fd33ebb71de83c3fd1c328ea84443b"
        propagate-environment: true
        environment: 
          - CACHE_BUCKET_NAME
        volumes:
         - "/var/lib/buildkite-agent/plugins/bash-cache:/bash-cache"

steps:
  - label: "checkstyle"
    <<: *docker-container
    command: ".buildkite/commands/checkstyle.sh"
    artifact_paths:
      - "**/build/reports/checkstyle/checkstyle.*"

  - label: "detekt"
    <<: *docker-container
    command: |
      echo "--- ðŸ§¹ Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew detektAll
    artifact_paths:
      - "**/build/reports/detekt/detekt.html"

  - label: "lint"
    <<: *docker-container
    command: |
      echo "--- ðŸ§¹ Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew lintVanillaRelease
    artifact_paths:
      - "**/build/reports/lint-results*.*"

  - label: "Test WooCommerce"
    <<: *docker-container
    command: |
      echo "--- ðŸ§ª Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew testVanillaRelease

  - label: "Test CardReaderModule"
    <<: *docker-container
    command: |
      echo "--- ðŸ§ª Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew lib:cardreader:testRelease

  - label: "Ensure Screenshot Tests Build"
    <<: *docker-container
    command: |
      echo "--- âš’ï¸ Building"
      cp gradle.properties-example gradle.properties
      ./gradlew assembleVanillaDebugAndroidTest